permit_join:
  description: Allow pairing new device.

refresh_device:
  description: >
    Refresh a device by sending many requests to it.
    Be aware that devices running on battery need to be woken up to answer,
    typically by pushing the pairing button.
    You should provide the entity_id OR the addr.
    If no parameter is provided, every devices will be refreshed.
  fields:
    entity_id:
      description: The device entity_id to refresh
      example: 'zigate.af7d'
    addr:
      description: ZiGate address of the device.
      example: 'af7d'

raw_command:
  description: Send a raw command to zigate.
  fields:
    cmd:
      description: Command code
      example: '0x0092'
    data:
      description: Payload in hex format.
      example: '02af7d010101'
      