permit_join:
  description: Allow pairing new device.

refresh_device:
  description: >
    Refresh a device by sending many requests to it.
    Be aware that devices running on battery need to be woken up to answer,
    typically by pushing the pairing button.
    You should provide the entity_id OR the addr OR the ieee.
    If no parameter is provided, every devices will be refreshed.
  fields:
    entity_id:
      description: The device entity_id to refresh
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: 'af7d'
    ieee:
      description: IEEE address of the device.
      example: '0123456789abcdef'
      
remove_device:
  description: >
    Remove a device.
    You should provide the entity_id OR the addr OR the ieee.
  fields:
    entity_id:
      description: The device entity_id to remove
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: 'af7d'
    ieee:
      description: IEEE address of the device.
      example: '0123456789abcdef'
      
identify_device:
  description: >
    Automatically identify a device's destination endpoint.
    Be aware that devices running on battery need to be woken up to answer,
    typically by pushing the pairing button.
    You should provide the entity_id OR the addr OR the ieee.
  fields:
    entity_id:
      description: The device entity_id to identify
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: 'af7d'
    ieee:
      description: IEEE address of the device.
      example: '0123456789abcdef'

raw_command:
  description: Send a raw command to zigate.
  fields:
    cmd:
      description: Command code
      example: '0x0092'
    data:
      description: Payload in hex format.
      example: '02af7d010101'
     
read_attribute:
  description: >
    Read attribute from device
    You should provide the entity_id OR the addr OR the ieee.
  fields:
    entity_id:
      description: The device entity_id to identify
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: 'af7d'
    ieee:
      description: IEEE address of the device.
      example: '0123456789abcdef'
    attribute_id:
      description: Attribute ID to read.
      example: '0xFF0D'
    manufacturer_code:
      description: Optionnal Manufacturer Code.
      example: '0x115F'
      default: '0'
      
write_attribute:
  description: >
    Read attribute from device
    You should provide the entity_id OR the addr OR the ieee.
  fields:
    entity_id:
      description: The device entity_id to identify
      example: 'zigate.0123456789abcdef'
    addr:
      description: ZiGate address of the device.
      example: 'af7d'
    ieee:
      description: IEEE address of the device.
      example: '0123456789abcdef'
    attribute_id:
      description: Attribute ID to write.
      example: '0xFF0D'
    value:
       description: Value to write
       example: '0x01'
    attribute_type:
      description: Attribute type to write.
      example: '0x20'
    manufacturer_code:
      description: Optionnal Manufacturer Code.
      example: '0x115F'
      